name: Build geosite.dat
on:
  workflow_dispatch:
  schedule:
    - cron: "30 21 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: ./go.mod

      - name: Checkout 1-stream/1stream-public-utils
        uses: actions/checkout@v6
        with:
          repository: 1-stream/1stream-public-utils
          path: media

      - name: Download Geosite and Geoview
        run: |
          mkdir -p tmp
          wget -O ./tmp/geosite.dat https://github.com/Loyalsoldier/v2ray-rules-dat/raw/release/geosite.dat
          wget -O ./tmp/geoview https://github.com/snowie2000/geoview/releases/download/0.2.6/geoview-linux-amd64
          chmod +x ./tmp/geoview

      - name: Prepare the build data
        run: |
          cp ./generate.sh ./media/generate.sh
          cd media
          mkdir data
          chmod +x generate.sh
          ./generate.sh
          ../tmp/geoview -input ../tmp/geosite.dat -type geosite -list "CATEGORY-COMPANIES@cn" -output ./data/company-cn
          ../tmp/geoview -input ../tmp/geosite.dat -type geosite -list "private" -output ./data/private 
          curl https://raw.githubusercontent.com/v2fly/domain-list-community/refs/heads/master/data/steam | grep "@cn" | sed "s/@cn//"  | sed "s/^.*://" > ./data/game-cn
          curl https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/SteamCN/SteamCN.list | grep "^DOMAIN" | sed "s/^DOMAIN.*,//" >> ./data/game-cn
          curl https://raw.githubusercontent.com/v2fly/domain-list-community/refs/heads/master/data/category-game-platforms-download | grep "@cn" | sed "s/@cn//"  | sed "s/^.*://" >> ./data/game-cn
          curl https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Game/GameDownloadCN/GameDownloadCN.list | grep "^DOMAIN" | sed "s/^DOMAIN.*,//" >> ./data/game-cn
          cp ../{data/cn,data/cn-list,data/media} ./data/

      - name: Get dependencies and run
        run: |
          go run ./ --datapath=./media/data --exportlists="game-cn,media,company-cn" --excludeattrs="" --togfwlist="steam,youtube"
      
      - name: Generate sha256 hashsum
        run: |
          cd publish || exit 1
          sha256sum geosite.dat > geosite.dat.sha256sum

      - name: Git push assets to "release" branch
        run: |
          cd publish || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add publish "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f publish release

      - name: Release and upload assets
        uses: softprops/action-gh-release@v3
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: |
            ./publish/geosite.dat
            ./publish/geosite.dat.sha256sum
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
